# -*- coding: utf-8 -*-
"""Lecture_01_1min_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15e4EGjeL97KZHXpsF1R8d_8WdAn5vHUe

# 🐍 **What is Python?**

➡ **Python is a high-level programming language.**

➡ **Python is easy to learn and read, almost like English.**


➡ **It is used in AI, websites, games, Automation and data science.**

# **But how does Python actually work internally?**
▶ **When you write Python code, the computer does NOT understand it directly.**

▶ **Computers only understand 0 and 1.**

▶ **First, the Python Interpreter reads your code line by line.**

▶ **Then it converts your code into bytecode (a middle language).**

▶ **After that, the Python Virtual Machine (PVM) runs the bytecode and gives output.**

# **Human Code → Python Interpreter → Bytecode → PVM → Computer Output**
"""